version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: ilk-kontakt-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: **
      POSTGRES_PASSWORD: **
      POSTGRES_DB: ilk-kontakt-postgresdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

