version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: ilk-kontakt-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: someuser # This will be ignored because we create it in the script.
      POSTGRES_PASSWORD: somepassword # This will be ignored because we create it in the script.
      POSTGRES_DB: somedb # This will be ignored because we create it in the script.
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

